config/routes.rb
Rails.application.routes.draw do
  resources :cosmetics
  resources :category
  resources :cart, only: %i[create destroy]
  devise_for :customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    get "success", to: "checkout#success", as: "checkout_success"
  end

  root to: "cosmetics#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :cosmetics, dependent: :destroy
  validates :name, presence: true
end

app/models/cosmetic.rb
class Cosmetic < ApplicationRecord
  # validates :name, :description, :type, :rarity, presence: true
  has_one_attached :image

  belongs_to :category, optional: true

  validates :name, presence: true

  def self.search(search, search_category)
    if search
      Cosmetic.where("name LIKE ? AND category = ?", "%#{search}%", search_category.to_s)
    else
      Cosmetic.all
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true
  has_one_attached :image
  has_many :orders, dependent: :destroy
  belongs_to :province, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_one :province, dependent: :destroy
  has_one :cosmetic, dependent: :destroy
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers, dependent: :destroy
  validates :name, :pst_rate, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_customer!
  before_action :initialize_session
  helper_method :cart
  helper_method :categories

  private

  def categories
    Category.all
  end

  def initialize_session
    # initialize the shopping cart
    session[:shopping_cart] ||= [] # Cosmetic id's will populate the array
  end

  def cart
    # Return a collection of product objects
    Cosmetic.find(session[:shopping_cart])
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name province_id address])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name province_id address])
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  # POST /cart
  def create
    # Add params[:id] to cart
    # logger.debug("Adding #{params[:id]} to the cart")
    id = params[:id].to_i

    unless session[:shopping_cart].include?(id)
      session[:shopping_cart] << id
      flash[:notice] = "Item added to cart"
    end

    redirect_to root_path
  end

  # DELETE /cart/:id
  def destroy
    # Remove params[:id] from cart
    id = params[:id].to_i
    session[:shopping_cart].delete(id)
    cosmetic = Cosmetic.find(id)
    flash[:notice] = "#{cosmetic.name} removed from cart"
    redirect_to root_path
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    @categories = Category.order(:name)
  end

  def show
    @category = Category.find(params[:id])
    # @category = Category.where(category_id: @category_id)
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    # cosmetic = Cosmetic.find(session[:shopping_cart])
    cosmetic_single = Cosmetic.find(params[:id])
    session[:cosmetic_id] = cosmetic_single.id

    province_tax = Province.find_by(id: current_customer.province_id)

    if cosmetic_single.nil?
      redirect_to root_path
      return
    end

    @session = Stripe::Checkout::Session.create(
      payment_method_types: ["card"],
      customer_email:       current_customer.email,
      line_items:           [{
        name:        cosmetic_single.name,
        description: cosmetic_single.description,
        amount:      cosmetic_single.price,
        currency:    "cad",
        quantity:    1
      },
                             {
                               name:        "PST",
                               description: "#{province_tax.name} Provincial Sales Tax",
                               amount:      (cosmetic_single.price * province_tax.pst_rate).round.to_i,
                               currency:    "cad",
                               quantity:    1
                             },
                             {
                               name:        "GST/HST",
                               description: "Government Sales Tax or Harmonized Sales Tax",
                               amount:      (cosmetic_single.price * province_tax.gst_hst_rate).round.to_i,
                               currency:    "cad",
                               quantity:    1
                             }],
      success_url:          checkout_success_url + "?session_id={CHECKOUT_SESSION_ID}",
      cancel_url:           checkout_cancel_url
    )

    respond_to do |format|
      format.js # render create.js.erb
    end
  end

  def success
    @session = Stripe::Checkout::Session.retrieve({ id: params[:session_id], expand: ["line_items"] })
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    @cosmetic_id = @cosmetic_instance
  end

  def cancel; end
end

app/controllers/cosmetics_controller.rb
class CosmeticsController < ApplicationController
  def index
    @q = Cosmetic.ransack(params[:q])
    @cosmetics = @q.result.page params[:page]
  end

  def show
    @cosmetic = Cosmetic.find(params[:id])
  end
end

app/controllers/province_controller.rb
class ProvinceController < ApplicationController
  def index
    @provinces = Province.all
  end

  def show
    @province = Province.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/cosmetics_helper.rb
module CosmeticsHelper
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/views/category/index.html.erb
<h3 class="title is-4">Categories</h3>

<% @categories.each do |category| %>
  <p><%= link_to category.name, category %></p>
<% end %>

app/views/category/show.html.erb
<h1 class="title is-1"><%= @category.name %></h1>
<em><%= link_to "Home", root_path %></em>

<div class="columns is-multiline">
  <div class="column">
    <div class="card">
      <div class="card-content">
        <% @category.cosmetics.each do |cosmetic| %>
          <h2 class="card-header-title"><%= link_to cosmetic.name, cosmetic %></h2>
            <% if cosmetic.image.present? %>
              <div class="card-image">
                <figure class="image is-200x200">
                  <%= image_tag cosmetic.image %>
                </figure>
              </div>
            <% end %>
              <p>
              <%= cosmetic.description %>
              </p>
            <footer class="card-footer">
              <p class="card-footer-item">
                <%= cosmetic.item_type %>
              </p>
              <p class="card-footer-item">
                <%= cosmetic.rarity %>
              </p>
            </footer>
            <%end%>
        </div>
      </div>
    </div>
  </div>

app/views/checkout/create.js.erb
const stripe = Stripe("<%= Rails.configuration.stripe[:publishable_key] %>");

stripe.redirectToCheckout({
  sessionId: "<%= @session.id %>"
}).then (function (result){
  console.log(result.error.message);
});

app/views/checkout/success.html.erb
<h1>Successful transaction!</h1>

<%= debug = @session %>
,<strong>payment intent</strong>
<%= debug = @payment_intent %>

<% payment_id = @payment_intent.id %>

<% customer = Customer.find(current_customer.id)%>%
<% province_tax = Province.find_by(id: customer.province_id)%>
<%= tax_cost = @session.line_items.data[1]["amount_total"] + @session.line_items.data[2]["amount_total"] %>

<% order = Order.create(
  payment_id:  @payment_intent.id,
  cosmetic_id: session[:cosmetic_id],
  customer_id: customer.id,
  province_id: province_tax.id,
  cosmetic_cost: @session.line_items.data[0]["amount_total"],
  tax_cost:    tax_cost,
  total_cost:  @payment_intent.amount_received,
  order_status: "paid")
%>

<strong>payment id</strong>
<%= @payment_intent.id %>
<br/>

<strong>cosmetic id</strong>
  <%= session[:cosmetic_id]%>
<br/>

  <strong>customer id</strong>
  <%= customer.id %>
<br/>

<strong>province id</strong>
  <%= province_tax.id%>
<br/>

<strong>price</strong>
<%= @session.line_items.data[0]["amount_total"] %>
<br/>

<strong>PST TAX</strong>
<%= @session.line_items.data[1]["amount_total"] %>
<br/>

<Strong>GST </Strong>
<%= @session.line_items.data[2]["amount_total"] %>
<br/>

<strong>COMBINED</strong>
<%= tax_cost %>
<br/>

<strong>TOTAL COST  </strong>
<%= @payment_intent.amount_received %>

app/views/cosmetics/_cosmetic.html.erb
<div class="column">
  <div class="card">
    <div class="card-content">
      <h2 class="card-header-title"><%= link_to cosmetic.name, cosmetic %></h2>
        <% if cosmetic.image.present? %>
          <div class="card-image">
            <figure class="image is-200x200">
              <%= image_tag cosmetic.image %>
            </figure>
          </div>
        <% end %>
          <p>
          <%= cosmetic.description %>
          </p>
        <footer class="card-footer">
          <p class="card-footer-item">
            <%= cosmetic.item_type %>
          </p>
          <p class="card-footer-item">
            <%= cosmetic.rarity %>
          </p>
        </footer>
        <aside>
          <% if cart.include?(cosmetic) %>
            <%= button_to cart_path(cosmetic), method: :delete do %>
              ❌Remove From Cart
            <% end %>
          <% else %>
          <%= form_with url: cart_index_path do %>
            <%= hidden_field_tag(:id, cosmetic.id) %>
            <%= button_tag '➕ Add to Cart' %>
            <% end %>
          <% end %>
        </aside>
        <%= button_to 'Buy Now!', checkout_create_path, method: :post, params: { id: cosmetic.id }, remote: true %>
    </div>
  </div>
</div>

app/views/cosmetics/index.html.erb
<%= button_to 'Buy Now!', checkout_create_path, method: :post, params: { id: @cosmetics.ids }, remote: true %>
<h1 class="title is-1">Fortnite Cosmetics!</h1>

<ul>
<li><%= link_to "See all categories", "category#index" %></li>
</ul>

<%= search_form_for @q do |f| %>

  <%= f.search_field :name_cont %>

<%= f.collection_select :category_id_eq, Category.all, :id, :name, include_blank: true %>
  <%= f.submit %>
<% end %>

<div class= "columns is-multiline">
<%= render partial: 'cosmetic', collection: @cosmetics %>
</div>
<%= paginate @cosmetics %>

app/views/cosmetics/show.html.erb
<div class="columns">
  <%= render partial: 'cosmetic',
             object: @cosmetic,
             locals: { show_link: false } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FortniteEcommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <nav>
    <ul>
        <li>
          cart
          <% if cart.present? %>
            <sup> <%= cart.size %> </sup>
              <ul>
              <% cart.each do |cosmetic| %>
                <li>
                  <%= cosmetic.name %> <%= link_to '❌', cart_path(cosmetic), method: :delete %>
                </li>
                <% end %>
              </ul>
          <% end %>
        </li>
    </ul>
  </nav>
  </header>
  <% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
  <% end %>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>

    <p class="navbar-text float-right">
<% if customer_signed_in? %>
  Logged in as <strong><%= current_customer.email %></strong>.
  <%= link_to 'Edit profile', edit_customer_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_customer_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_customer_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_customer_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

  </body>
</html>